default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "default"
      threads: 5
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1
    - queues: "low"
      threads: 1
      processes: 1
      polling_interval: 5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
